// <auto-generated />
using System;
using ApiWykazuPodatnikowVatData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWykazuPodatnikowVatData.Migrations
{
    [DbContext(typeof(ApiWykazuPodatnikowVatDataDbContext))]
    partial class ApiWykazuPodatnikowVatDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiWykazuPodatnikowVatDataEntityPeselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizedClerks")
                        .HasColumnName("AuthorizedClerks")
                        .HasColumnType("text")
                        .HasMaxLength(2147483647);

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<bool>("HasVirtualAccounts")
                        .HasColumnName("HasVirtualAccounts")
                        .HasColumnType("bit");

                    b.Property<string>("Krs")
                        .HasColumnName("Krs")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Nip")
                        .HasColumnName("Nip")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Partners")
                        .HasColumnName("Partners")
                        .HasColumnType("text")
                        .HasMaxLength(2147483647);

                    b.Property<string>("RegistrationDenialBasis")
                        .HasColumnName("RegistrationDenialBasis")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RegistrationDenialDate")
                        .HasColumnName("RegistrationDenialDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("RegistrationLegalDate")
                        .HasColumnName("RegistrationLegalDate")
                        .HasColumnType("date");

                    b.Property<string>("Regon")
                        .HasColumnName("Regon")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("RemovalBasis")
                        .HasColumnName("RemovalBasis")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RemovalDate")
                        .HasColumnName("RemovalDate")
                        .HasColumnType("date");

                    b.Property<string>("Representatives")
                        .HasColumnName("Representatives")
                        .HasColumnType("text")
                        .HasMaxLength(2147483647);

                    b.Property<string>("ResidenceAddress")
                        .HasColumnName("ResidenceAddress")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("RestorationBasis")
                        .HasColumnName("RestorationBasis")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RestorationDate")
                        .HasColumnName("RestorationDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusVat")
                        .HasColumnName("StatusVat")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("WorkingAddres")
                        .HasColumnName("WorkingAddress")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ApiWykazuPodatnikowVatDataEntityPeselId");

                    b.ToTable("ApiWykazuPodatnikowVatDataEntity","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityAccountNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnName("AccountNumber")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<Guid?>("ApiWykazuPodatnikowVatDataEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ApiWykazuPodatnikowVatDataEntityId");

                    b.ToTable("ApiWykazuPodatnikowVatDataEntityAccountNumber","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiWykazuPodatnikowVatDataEntityAuthorizedClerksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiWykazuPodatnikowVatDataEntityPartnersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiWykazuPodatnikowVatDataEntityPeselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiWykazuPodatnikowVatDataEntityRepresentativesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnName("CompanyName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("varchar(160)")
                        .HasMaxLength(160);

                    b.Property<string>("Nip")
                        .HasColumnName("Nip")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("ApiWykazuPodatnikowVatDataEntityAuthorizedClerksId");

                    b.HasIndex("ApiWykazuPodatnikowVatDataEntityPartnersId");

                    b.HasIndex("ApiWykazuPodatnikowVatDataEntityPeselId");

                    b.HasIndex("ApiWykazuPodatnikowVatDataEntityRepresentativesId");

                    b.ToTable("ApiWykazuPodatnikowVatDataEntityPerson","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityPesel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnName("Pesel")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.ToTable("ApiWykazuPodatnikowVatDataEntityPesel","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntity", b =>
                {
                    b.HasOne("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityPesel", "Pesel")
                        .WithMany("ApiWykazuPodatnikowVatDataEntity")
                        .HasForeignKey("ApiWykazuPodatnikowVatDataEntityPeselId");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityAccountNumber", b =>
                {
                    b.HasOne("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntity", "ApiWykazuPodatnikowVatDataEntity")
                        .WithMany("ApiWykazuPodatnikowVatDataEntityAccountNumber")
                        .HasForeignKey("ApiWykazuPodatnikowVatDataEntityId");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityPerson", b =>
                {
                    b.HasOne("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntity", "AuthorizedClerk")
                        .WithMany("AuthorizedClerk")
                        .HasForeignKey("ApiWykazuPodatnikowVatDataEntityAuthorizedClerksId");

                    b.HasOne("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntity", "Partner")
                        .WithMany("Partner")
                        .HasForeignKey("ApiWykazuPodatnikowVatDataEntityPartnersId");

                    b.HasOne("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntityPesel", "Pesel")
                        .WithMany("ApiWykazuPodatnikowVatDataEntityPerson")
                        .HasForeignKey("ApiWykazuPodatnikowVatDataEntityPeselId");

                    b.HasOne("ApiWykazuPodatnikowVatData.Models.ApiWykazuPodatnikowVatDataEntity", "Representative")
                        .WithMany("Representative")
                        .HasForeignKey("ApiWykazuPodatnikowVatDataEntityRepresentativesId");
                });
#pragma warning restore 612, 618
        }
    }
}
