// <auto-generated />
using System;
using ApiWykazuPodatnikowVatData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWykazuPodatnikowVatData.Migrations
{
    [DbContext(typeof(ApiWykazuPodatnikowVatDataDbContext))]
    partial class ApiWykazuPodatnikowVatDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizedClerks")
                        .HasColumnName("AuthorizedClerks")
                        .HasColumnType("text")
                        .HasMaxLength(2147483647);

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("EntityPeselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasVirtualAccounts")
                        .HasColumnName("HasVirtualAccounts")
                        .HasColumnType("bit");

                    b.Property<string>("Krs")
                        .HasColumnName("Krs")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Nip")
                        .HasColumnName("Nip")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Partners")
                        .HasColumnName("Partners")
                        .HasColumnType("text")
                        .HasMaxLength(2147483647);

                    b.Property<string>("RegistrationDenialBasis")
                        .HasColumnName("RegistrationDenialBasis")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RegistrationDenialDate")
                        .HasColumnName("RegistrationDenialDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("RegistrationLegalDate")
                        .HasColumnName("RegistrationLegalDate")
                        .HasColumnType("date");

                    b.Property<string>("Regon")
                        .HasColumnName("Regon")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("RemovalBasis")
                        .HasColumnName("RemovalBasis")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RemovalDate")
                        .HasColumnName("RemovalDate")
                        .HasColumnType("date");

                    b.Property<string>("Representatives")
                        .HasColumnName("Representatives")
                        .HasColumnType("text")
                        .HasMaxLength(2147483647);

                    b.Property<string>("ResidenceAddress")
                        .HasColumnName("ResidenceAddress")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("RestorationBasis")
                        .HasColumnName("RestorationBasis")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("RestorationDate")
                        .HasColumnName("RestorationDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusVat")
                        .HasColumnName("StatusVat")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("WorkingAddres")
                        .HasColumnName("WorkingAddress")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("EntityPeselId");

                    b.ToTable("Entity","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.EntityAccountNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnName("AccountNumber")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("EntityAccountNumber","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.EntityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountAssigned")
                        .HasColumnName("AccountAssigned")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3);

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnName("RequestDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestId")
                        .HasColumnName("RequestId")
                        .HasColumnType("varchar(18)")
                        .HasMaxLength(18);

                    b.HasKey("Id");

                    b.ToTable("EntityCheck","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.EntityPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnName("CompanyName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("EntityAuthorizedClerksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntityPartnersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntityPeselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntityRepresentativesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("varchar(160)")
                        .HasMaxLength(160);

                    b.Property<string>("Nip")
                        .HasColumnName("Nip")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("EntityAuthorizedClerksId");

                    b.HasIndex("EntityPartnersId");

                    b.HasIndex("EntityPeselId");

                    b.HasIndex("EntityRepresentativesId");

                    b.ToTable("EntityPerson","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.EntityPesel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnName("DateOfCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DateOfModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnName("Pesel")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.ToTable("EntityPesel","ApiWykazuPodatnikowVat");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.Entity", b =>
                {
                    b.HasOne("ApiWykazuPodatnikowVatData.Models.EntityPesel", "Pesel")
                        .WithMany("Entity")
                        .HasForeignKey("EntityPeselId");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.EntityAccountNumber", b =>
                {
                    b.HasOne("ApiWykazuPodatnikowVatData.Models.Entity", "Entity")
                        .WithMany("EntityAccountNumber")
                        .HasForeignKey("EntityId");
                });

            modelBuilder.Entity("ApiWykazuPodatnikowVatData.Models.EntityPerson", b =>
                {
                    b.HasOne("ApiWykazuPodatnikowVatData.Models.Entity", "AuthorizedClerk")
                        .WithMany("AuthorizedClerk")
                        .HasForeignKey("EntityAuthorizedClerksId");

                    b.HasOne("ApiWykazuPodatnikowVatData.Models.Entity", "Partner")
                        .WithMany("Partner")
                        .HasForeignKey("EntityPartnersId");

                    b.HasOne("ApiWykazuPodatnikowVatData.Models.EntityPesel", "Pesel")
                        .WithMany("EntityPerson")
                        .HasForeignKey("EntityPeselId");

                    b.HasOne("ApiWykazuPodatnikowVatData.Models.Entity", "Representative")
                        .WithMany("Representative")
                        .HasForeignKey("EntityRepresentativesId");
                });
#pragma warning restore 612, 618
        }
    }
}
