// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiWykazuPodatnikowVatData.EF.Models
{
    [Table("ApiWykazuPodatnikowVatDataEntityPesel", Schema = "ApiWykazuPodatnikowVat")]
    public partial class ApiWykazuPodatnikowVatDataEntityPesel
    {
        public ApiWykazuPodatnikowVatDataEntityPesel()
        {
            ApiWykazuPodatnikowVatDataEntity = new HashSet<ApiWykazuPodatnikowVatDataEntity>();
            ApiWykazuPodatnikowVatDataEntityPerson = new HashSet<ApiWykazuPodatnikowVatDataEntityPerson>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(11)]
        public string Pesel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOfCreate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfModification { get; set; }

        [InverseProperty("ApiWykazuPodatnikowVatDataEntityPesel")]
        public virtual ICollection<ApiWykazuPodatnikowVatDataEntity> ApiWykazuPodatnikowVatDataEntity { get; set; }
        [InverseProperty("ApiWykazuPodatnikowVatDataEntityPesel")]
        public virtual ICollection<ApiWykazuPodatnikowVatDataEntityPerson> ApiWykazuPodatnikowVatDataEntityPerson { get; set; }
    }
}