// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiWykazuPodatnikowVatData.EF.Models
{
    [Table("ApiWykazuPodatnikowVatDataEntityAccountNumber", Schema = "ApiWykazuPodatnikowVat")]
    public partial class ApiWykazuPodatnikowVatDataEntityAccountNumber
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(32)]
        public string AccountNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOfCreate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfModification { get; set; }
        public Guid? ApiWykazuPodatnikowVatDataEntityId { get; set; }

        [ForeignKey(nameof(ApiWykazuPodatnikowVatDataEntityId))]
        [InverseProperty("ApiWykazuPodatnikowVatDataEntityAccountNumber")]
        public virtual ApiWykazuPodatnikowVatDataEntity ApiWykazuPodatnikowVatDataEntity { get; set; }
    }
}