// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiWykazuPodatnikowVatData.EF.Models
{
    [Table("ApiWykazuPodatnikowVatDataEntity", Schema = "ApiWykazuPodatnikowVat")]
    public partial class ApiWykazuPodatnikowVatDataEntity
    {
        public ApiWykazuPodatnikowVatDataEntity()
        {
            ApiWykazuPodatnikowVatDataEntityAccountNumber = new HashSet<ApiWykazuPodatnikowVatDataEntityAccountNumber>();
            ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityAuthorizedClerks = new HashSet<ApiWykazuPodatnikowVatDataEntityPerson>();
            ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityPartners = new HashSet<ApiWykazuPodatnikowVatDataEntityPerson>();
            ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityRepresentatives = new HashSet<ApiWykazuPodatnikowVatDataEntityPerson>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(256)]
        public string Name { get; set; }
        [StringLength(10)]
        public string Nip { get; set; }
        [StringLength(32)]
        public string StatusVat { get; set; }
        [StringLength(14)]
        public string Regon { get; set; }
        public Guid? ApiWykazuPodatnikowVatDataEntityPeselId { get; set; }
        [StringLength(10)]
        public string Krs { get; set; }
        [StringLength(200)]
        public string ResidenceAddress { get; set; }
        [StringLength(200)]
        public string WorkingAddress { get; set; }
        [Column(TypeName = "text")]
        public string Representatives { get; set; }
        [Column(TypeName = "text")]
        public string AuthorizedClerks { get; set; }
        [Column(TypeName = "text")]
        public string Partners { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RegistrationLegalDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RegistrationDenialDate { get; set; }
        [StringLength(200)]
        public string RegistrationDenialBasis { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RestorationDate { get; set; }
        [StringLength(200)]
        public string RestorationBasis { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RemovalDate { get; set; }
        [StringLength(200)]
        public string RemovalBasis { get; set; }
        public bool HasVirtualAccounts { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOfCreate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfModification { get; set; }

        [ForeignKey(nameof(ApiWykazuPodatnikowVatDataEntityPeselId))]
        [InverseProperty("ApiWykazuPodatnikowVatDataEntity")]
        public virtual ApiWykazuPodatnikowVatDataEntityPesel ApiWykazuPodatnikowVatDataEntityPesel { get; set; }

        [InverseProperty("ApiWykazuPodatnikowVatDataEntity")]
        public virtual ICollection<ApiWykazuPodatnikowVatDataEntityAccountNumber> ApiWykazuPodatnikowVatDataEntityAccountNumber { get; set; }

        [InverseProperty(nameof(ApiWykazuPodatnikowVatDataEntityPerson.ApiWykazuPodatnikowVatDataEntityAuthorizedClerks))]
        public virtual ICollection<ApiWykazuPodatnikowVatDataEntityPerson> ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityAuthorizedClerks { get; set; }
        [InverseProperty(nameof(ApiWykazuPodatnikowVatDataEntityPerson.ApiWykazuPodatnikowVatDataEntityPartners))]
        public virtual ICollection<ApiWykazuPodatnikowVatDataEntityPerson> ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityPartners { get; set; }
        [InverseProperty(nameof(ApiWykazuPodatnikowVatDataEntityPerson.ApiWykazuPodatnikowVatDataEntityRepresentatives))]
        public virtual ICollection<ApiWykazuPodatnikowVatDataEntityPerson> ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityRepresentatives { get; set; }
    }
}