// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiWykazuPodatnikowVatData.EF.Models
{
    [Table("ApiWykazuPodatnikowVatDataEntityPerson", Schema = "ApiWykazuPodatnikowVat")]
    public partial class ApiWykazuPodatnikowVatDataEntityPerson
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? ApiWykazuPodatnikowVatDataEntityRepresentativeId { get; set; }
        public Guid? ApiWykazuPodatnikowVatDataEntityAuthorizedClerkId { get; set; }
        public Guid? ApiWykazuPodatnikowVatDataEntityPartnerId { get; set; }
        public Guid? ApiWykazuPodatnikowVatDataEntityPeselId { get; set; }
        [StringLength(256)]
        public string CompanyName { get; set; }
        [StringLength(60)]
        public string FirstName { get; set; }
        [StringLength(160)]
        public string LastName { get; set; }
        [StringLength(10)]
        public string Nip { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOfCreate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfModification { get; set; }

        [ForeignKey(nameof(ApiWykazuPodatnikowVatDataEntityAuthorizedClerkId))]
        [InverseProperty(nameof(ApiWykazuPodatnikowVatDataEntity.ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityAuthorizedClerks))]
        public virtual ApiWykazuPodatnikowVatDataEntity ApiWykazuPodatnikowVatDataEntityAuthorizedClerks { get; set; }
        [ForeignKey(nameof(ApiWykazuPodatnikowVatDataEntityPartnerId))]
        [InverseProperty(nameof(ApiWykazuPodatnikowVatDataEntity.ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityPartners))]
        public virtual ApiWykazuPodatnikowVatDataEntity ApiWykazuPodatnikowVatDataEntityPartners { get; set; }
        [ForeignKey(nameof(ApiWykazuPodatnikowVatDataEntityPeselId))]
        [InverseProperty("ApiWykazuPodatnikowVatDataEntityPerson")]
        public virtual ApiWykazuPodatnikowVatDataEntityPesel ApiWykazuPodatnikowVatDataEntityPesel { get; set; }
        [ForeignKey(nameof(ApiWykazuPodatnikowVatDataEntityRepresentativeId))]
        [InverseProperty(nameof(ApiWykazuPodatnikowVatDataEntity.ApiWykazuPodatnikowVatDataEntityPersonApiWykazuPodatnikowVatDataEntityRepresentatives))]
        public virtual ApiWykazuPodatnikowVatDataEntity ApiWykazuPodatnikowVatDataEntityRepresentatives { get; set; }
    }
}